// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACED_BY_YOUR_API_KEY',
    appId: '1:956594813721:web:473aa7b4e9de4a7343a388',
    messagingSenderId: '956594813721',
    projectId: 'iot-flutter-d8dad',
    authDomain: 'iot-flutter-d8dad.firebaseapp.com',
    databaseURL: 'https://iot-flutter-d8dad-default-rtdb.firebaseio.com',
    storageBucket: 'iot-flutter-d8dad.firebasestorage.app',
    measurementId: 'G-1J3V4B6JZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACED_BY_YOUR_API_KEY',
    appId: '1:956594813721:android:9c82c97da5871bfb43a388',
    messagingSenderId: '956594813721',
    projectId: 'iot-flutter-d8dad',
    databaseURL: 'https://iot-flutter-d8dad-default-rtdb.firebaseio.com',
    storageBucket: 'iot-flutter-d8dad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACED_BY_YOUR_API_KEY',
    appId: '1:956594813721:ios:50752614a733601643a388',
    messagingSenderId: '956594813721',
    projectId: 'iot-flutter-d8dad',
    databaseURL: 'https://iot-flutter-d8dad-default-rtdb.firebaseio.com',
    storageBucket: 'iot-flutter-d8dad.firebasestorage.app',
    iosBundleId: 'com.example.modernSmartHomeUiPractical01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACED_BY_YOUR_API_KEY',
    appId: '1:956594813721:ios:50752614a733601643a388',
    messagingSenderId: '956594813721',
    projectId: 'iot-flutter-d8dad',
    databaseURL: 'https://iot-flutter-d8dad-default-rtdb.firebaseio.com',
    storageBucket: 'iot-flutter-d8dad.firebasestorage.app',
    iosBundleId: 'com.example.modernSmartHomeUiPractical01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACED_BY_YOUR_API_KEY',
    appId: '1:956594813721:web:4782474197beb13343a388',
    messagingSenderId: '956594813721',
    projectId: 'iot-flutter-d8dad',
    authDomain: 'iot-flutter-d8dad.firebaseapp.com',
    databaseURL: 'https://iot-flutter-d8dad-default-rtdb.firebaseio.com',
    storageBucket: 'iot-flutter-d8dad.firebasestorage.app',
    measurementId: 'G-Z7B9TDC28D',
  );
}
